### ISSUE TITLE
Integrate codacy for this repository

### ISSUE THREAD

**Issue by rajitha1998** [codeJunctionTeam/fire-call#4]
## Task to be done 
* Codacy is an Automated Code Review Tool that monitors your technical debt, helps you improve your code quality, teaches best practices to your developers, and helps you save time in Code Reviews

* For more Information - https://support.codacy.com/hc/en-us/articles/207278449-Setting-up-your-repository

**Comment by janethavi** [comment]
Webhook added by integrating this repository with Codacy.

**Comment by rajitha1998** [comment]
awesome  @janethavi. Shall I close the Issue?

**Comment by janethavi** [comment]
Yes @rajitha1998. You can close the issue.
